#!/bin/bash

docker run -it \
-v /Volumes/share/preprocess/data_input:/home/rstudio/data_input \
-v /Volumes/Share/preprocess/:/home/rstudio/workspace \
-p 2342:8787 chumbleycode/preprocess:latest bash
